config/routes.rb
Rails.application.routes.draw do
devise_for :users
devise_scope :user do
    root :to => "devise/sessions#new"
end

resources :users
resources :recipes do
  resources :comments, only: [:create, :destroy, :edit, :update]
end
resources :shops
resources :recipe_likes, only: [:create, :destroy]
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :name, presence: true,length: { maximum:20 }
  validates :address, presence: true,length: { maximum:50 }
  has_many :recipes, dependent: :destroy, inverse_of: :shop
  belongs_to :user
  accepts_nested_attributes_for :recipes, allow_destroy: true
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action:set_shop,only:[:edit,:update,:show,:destroy]
  before_action :authenticate_user!
  def index
    @s = Shop.ransack(params[:q])
    @shops = @s.result(distinct: true)
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to shops_path ,notice:'ショップを登録しました'
    else
      render 'new',notice:'登録に失敗しました'
    end
  end

  def destroy
    if current_user.id == @shop.user_id
      @shop.destroy
      redirect_to shops_path,notice:'削除しました'
    else
      redirect_to shops_path,notice:'権限がありません'
    end
  end

  def edit
    redirect_to shops_path unless current_user.id == @shop.user_id || current_user.admin == true
  end

  def update
    if
      @shop.update(shop_params)
      redirect_to shops_path,notice:"編集しました"
    else
      render 'edit'
    end
  end
end

def shop_params
  params.require(:shop).permit(:id,:name,:address,:recipe_id,:user_id)
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for @shop,  local: true do |f| %>
  <%= f.hidden_field:user_id, value: current_user.id %>
  <li><%= f.label :name %><%= f.text_field :name %></li>
  <li><%= f.label :address %><%= f.text_field :address %></li>
  <li><%= f.submit %></li>
  <div class="shop"><%= link_to t('view.back'), shops_path %></div>
<% end %>

app/views/shops/edit.html.erb
<div class="container">
  <div class="shop_new">
    <h2><%= t('shop.name') %>の<%= t('view.edit') %></h2>
          <%= render 'form' %>
    </div>
    <div class="shop"><%= link_to t('view.back'), shops_path %></div>
</div>

app/views/shops/index.html.erb
<div class="container">
<h2><%= t('shop.index')%></h2>
  <%= search_form_for @s do |s| %>
    <div><span  id="search"><%= link_to t('shop.new'), new_shop_path %></span>
    <span><%= s.label :name_cont, t('shop.name') %>
    <%= s.search_field :name_cont %>
    <%= s.submit t('header.search') %></span></div>
  <% end %>

  <div class="shop">
  <table class="shop_tbl  col-md-8">
    <tr><th><%= t('shop.name')%></th><th><%= t('shop.address') %></th><th><%= t('view.created')%></th><th><%= t('recipe.count')%></th><th></th><th></th></tr>
    <% @shops.each do |shop| %>
    <tr><td><%= shop.name %></td><td><%= shop.address %></td><td><%= shop.created_at.strftime('%Y/%m/%d') %></td><td><%= shop.recipes.count %></td>
    <td><%= link_to t('view.edit'),edit_shop_path(shop.id) if current_user.id == shop.user_id %></td>
    <td><%= link_to t('view.delete'),shop_path(shop.id), method: :delete if current_user.id == shop.user_id %></td></tr>
    <% end %>
  </table>
  </div>
</div>

app/views/shops/new.html.erb
<div class="container">
  <div class="shop">
    <h2><%= t('shop.new')%></h2>
      <% if @shop.errors.any? %>
          <ul>
          <% @shop.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>
          <%= render 'form' %>
  </div>
</div>