config/routes.rb
Rails.application.routes.draw do
devise_for :users
devise_scope :user do
    root :to => "devise/sessions#new"
end

resources :users
resources :recipes do
  resources :comments, only: [:create, :destroy, :edit, :update]
end
resources :shops
resources :recipe_likes, only: [:create, :destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, optional: true, inverse_of: :recipes
  belongs_to :shop, optional: true, inverse_of: :recipes
  validates :shop_id, presence: true 
  enum curry_type: {chicken: 0, pork: 1, beef: 2, fish: 3, vege: 4, other: 5}
  validates :name, presence: true ,length: { maximum:30 }
  validates :content, presence: true ,length: { maximum:100 }
  validates :curry_type, presence: true
  has_many :recipe_likes, dependent: :destroy
  has_many :likes_users, through: :recipe_likes, source: :user, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :materials, dependent: :destroy, inverse_of: :recipe
  accepts_nested_attributes_for :materials, allow_destroy: true
  has_many :flows, dependent: :destroy, inverse_of: :recipe
  accepts_nested_attributes_for :flows, allow_destroy: true
  mount_uploader :picture, ImageUploader
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action:set_recipe,only:[:edit,:update,:show,:destroy]
  before_action :authenticate_user!, only: [:index, :new, :create]
  def index
        @recipes　= Recipe.all.order(created_at: :desc)
  end

  def new
    @recipe = Recipe.new
    3.times{ @recipe.materials.build}
    3.times{ @recipe.flows.build }
  end

  def create
    @recipe = Recipe.new(recipe_params)
      if @recipe.save
        redirect_to recipes_path, notice:'レシピを投稿しました'
      else
        render 'new', notice:'レシピを投稿できませんでした'
      end
  end

  def destroy
    if  @recipe.destroy
      redirect_to recipes_path, notice:'削除しました'
    else
      redirect_to recipes_path, notice:'削除できません'
    end
  end

  def edit
      redirect_to recipes_path unless current_user.id == @recipe.user_id
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipes_path, notice:'レシピを編集しました'
    else
      render 'edit'
    end
  end

  def show
    @favorite = current_user.recipe_likes.find_by(recipe_id: @recipe.id)
    @comment = @recipe.comments.build
    @comments = @recipe.comments
  end

  private
  def recipe_params
    params.require(:recipe).permit(:id,:name,:picture,:content,:curry_type,:user_id,:shop_id, :remove_picture,
        materials_attributes: [:id,:name,:amount,:recipe_id,:_destroy],
        flows_attributes: [:id,:content,:picture,:recipe_id,:_destroy, :remove_picture]
      )
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def choose_new_or_edit
    if action_name == 'new'
      recipes_path
    elsif action_name == 'edit'
      recipe_path
    end
  end
end

app/views/recipes/_form.html.erb
<%= form_with model:@recipe, url: choose_new_or_edit, local: true do |f| %>
  <div class="row content">
  <div class="col-md-6">
   <div class="subject">データ</div>
      <table class="data">
        <% if @recipe.picture.url.present? %>
          <tr>
            <th></th><td><%= image_tag @recipe.picture.url %></td>
          </tr>
          <tr>
            <th><%= f.label t('view.delete') %></th>
            <td><%= f.check_box :remove_picture %></td>
          </tr>
        <% else %>
          <tr>
            <th><%= f.label t('recipe.picture') %></th>
            <td><%= f.file_field :picture %></td>
          </tr>
        <% end %>
        <%= f.hidden_field:user_id, value: current_user.id %>
        <tr>
          <th><%= f.label t('shop.name') %></th>
          <td><%= f.collection_select :shop_id, Shop.all, :id, :name, include_blank: false, prompt:true %></td>
        </tr>
        <tr>
          <th><%= f.label t('recipe.name') %></th>
          <td><%= f.text_field :name%></td>
        </tr>
        <tr>
          <th><%= f.label t('recipe.curry_type') %></th>
          <td><%= f.select :curry_type,
            Recipe.curry_types_i18n.keys.map{|k| [Recipe.curry_types_i18n[k], k]} , include_blank: false, prompt: true %></td>
        </tr>
      </table>
    </div>
    
    <div class="col-md-6">
        <p class="subject"><%= t('recipe.content') %></p>
        <p class="data"><%= f.text_area :content, placeholder: "１００文字以内" %></p>
      </div>
  </div>


<% #材料　%>
<div class="row">
  <div class="col-md-6">
    <div class="subject"><%=  t('material.name') %></div>
      <div class="add"><button type="button" class=" btn btn-warning btn-sm"><%= f.add_nested_fields_link :materials,  t('view.add'), role: 'button'%></button></div>
      <div class="data">
        <%= f.nested_fields_for :materials do |material| %>
          <div id="material"><span id="m_name"><%= material.text_field :name, placeholder: "材料名" %></span><span id="m_amount"><%= material.text_field :amount, placeholder: "分量" %></span>
          <button type="button" class=" btn btn-danger  btn-sm"><%= material.remove_nested_fields_link t('view.delete'), role: 'button' %></button></div>
        <% end %>
      </div>
  </div>

<% #調理方法　%>
  <div class="col-md-6">
    <div class="subject"><%= t('flow.content') %></div>
      <div class="add"><button type="button" class=" btn btn-warning btn-sm"><%= f.add_nested_fields_link :flows, t('view.add'), role: 'button'%></button></div>
      <div class="data" id="flow">
      <ol>
      <%= f.nested_fields_for :flows do |flow| %>
        <li><%= t('flow.content') %><span id="d_btn"><button type="button" class=" btn btn-danger btn-sm"><%= flow.remove_nested_fields_link  t('view.delete'), role: 'button' %></button></span></li>
          <span><%=  t('flow.picture') %><%= flow.file_field :picture %></span>
          <span><%= flow.text_area :content, placeholder: "１００文字以内" %></span>
      <% end %>
      </ol>
  </div>
  <div id="submit"><%= f.submit %><%= link_to "", recipes_path %></div>
</div>
<% end %>

app/views/recipes/edit.html.erb
<div class="container"> 
<h2><%= t('recipe.edit') %></h2>
  <% if @recipe.errors.any? %>
      <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
      <%= render 'form' %>
</div>

app/views/recipes/index.html.erb
<div class="container"> 
 <% @recipes.each do |recipe| %>
  <%= link_to recipe_path(recipe.id) do %>
  <div class="recipe_box">
    <div class="picture">
      <% if recipe.picture.url.present? %>
        <div><%= image_tag recipe.picture.url %></div>
      <% else %>
        <div><%= image_tag 'no_photo.png', size: '50x50' %></div>
      <% end %>
    </div>
    <div class="recipe_inf" >
      <ul>
        <li id="inf_1"><%= "#{recipe.shop.name}風" %><%= recipe.name %></li>
        <li id="inf_2"><%= t('view.post') %><%=  recipe.user.name %></li>
        <li id="inf_2"><%= t('view.update') %><%= recipe.updated_at.strftime('%Y/%m/%d') %></li>
      </ul>
    </div>
  </div>
  <% end %>
<% end %>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <h2><%= t('recipe.new')%></h2>
  <% if @recipe.errors.any? %>
      <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li class="error"><%= message %></li>
        <% end %>
      </ul>
  <% end %>
    <%= render 'form' %>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="subject">データ</div>
      <% if current_user.id == @recipe.user_id %>
          <div><span class="user_show"><%= link_to t('view.edit'),edit_recipe_path(@recipe.id)  %></span>
          <span class="user_show"><%= link_to t('view.delete'),recipe_path(@recipe.id), method: :delete %></span></div>
            <% end %>
        <div class="recipe_box_show">
          <div class="picture_show">
            <% if @recipe.picture.url.present? %>
              <%= image_tag @recipe.picture.url %>
            <% else %>
              <%= image_tag 'no_photo.png', size: '50x50' %>
            <% end %>
          </div>
          <div>
            <% unless @recipe.user_id == current_user.id %>
              <% if @favorite.present? %>
                <button type="button" class="btn btn-warning  btn-block"><%= link_to t('view.dislike'), recipe_like_path(id: @favorite.id), method: :delete %></button>
              <% else %>
                <button type="button"  class="btn btn-warning  btn-block" ><%= link_to t('view.like'),  recipe_likes_path(recipe_id: @recipe.id), method: :post %></button>
              <% end %>
            <% end %>
          </div>
          
        </div>
      </div>

    <div class="col-md-4">
      <div class="data_show">
        <table id="table_show">
          <tr><th><%= t('shop.name') %></th><td><%= Shop.find(@recipe.shop_id).name %></td></tr>
          <tr><th><%= t('recipe.name') %></th><td><%= @recipe.name %></td></tr>
          <tr><th><%= t('recipe.curry_type') %></th><td><%= @recipe.curry_type_i18n %></td></tr>
          <%= link_to t('recipe.new'),new_recipe_path %>
          <tr><th><%= t('view.post') %></th><td id="user_link"><%= link_to User.find(@recipe.user_id).name, user_path(@recipe.user_id) %></td></tr>
          <tr><th><%= t('view.update') %></th><td><%= @recipe.updated_at.strftime('%Y/%m/%d') %></td></tr>
        </table>
        <div id="content_show"><%= t('recipe.content') %></th><td><%= @recipe.content %></div>
      </div>
    </div>
     
    <div class="col-md-4">
      <div class="subject"><%= t('material.name') %></div>
      <table class="material_show"> 
          <div><tr><th><%= t('material.name') %></th><th><%= t('material.amount') %></th>
        <% @recipe.materials.each do |material|  %>
          <tr><td><%= material.name %></td><td><%= material.amount %></td></tr>
        <% end %>
      </table>
    </div>
  </div>
  
<div class="row">
<div class="subject"><%= t('flow.content') %></div>
<div class="flow_show">
<% @recipe.flows.each.with_index(1) do |flow,i|  %>
  <div class="col-md-4"> 
        <div><%= "#{i}" %>. <%= t('flow.content') %></div>
        <div class="picture_show">
            <% if flow.picture.url.present? %>
            <%= image_tag flow.picture.url %>
            <% else %>
           <%= image_tag 'no_photo.png', size:'50x50'%>
            <% end %>
        </div>
       <div id="flow_content"><%= flow.content %></div>
      </div>
    <% end %>
</div>
</div>

<div class="row">
  <div class="col-md-12">
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: {comments: @comments, recipe: @recipe} %>
    </div>
    <div><%= render partial: 'comments/form', locals: {comment: @comment, recipe: @recipe} %></div>
  </div>
  </div>
</div>