config/routes.rb
Rails.application.routes.draw do
devise_for :users
devise_scope :user do
    root :to => "devise/sessions#new"
end

resources :users
resources :recipes do
  resources :comments, only: [:create, :destroy, :edit, :update]
end
resources :shops
resources :recipe_likes, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true ,length: { maximum:255 }
  validates :email, presence: true ,length: { maximum:255 }
  has_many :recipes, dependent: :destroy, inverse_of: :user
  has_many :shops, dependent: :destroy, inverse_of: :user
  mount_uploader :picture, ImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipe_likes, dependent: :destroy, inverse_of: :user
  has_many :comments, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action:set_user,only:[:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def show
    @recipes = @user.recipes.all
    @recipe_likes =  current_user.recipe_likes
  end

  def edit
    redirect_to recipes_path unless current_user == @user || current_user.admin == true
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id),notice:"編集しました"
    else
      render 'edit'
    end
  end

  def destroy
    if current_user.id == @user.id
      @user.destroy
      redirect_to recipes_path,notice:'削除しました'
    else
      redirect_to recipes_path,notice:'権限がありません'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:picture,:remove_picture)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
<h2><%= t('user.edit') %></h2>
<% @user.errors.full_messages.each do |msg| %>
  <div><%= msg %></div>
<% end %>
<%= form_for @user do |f| %>
<table>
  <% if @user.picture.url.present? %>
    <tr>
      <th></th><td><%= image_tag @user.picture.url %></td>
    </tr>
    <tr>
      <th><%= f.label t('view.delete') %></th>
      <td><%= f.check_box :remove_picture %></td>
    </tr>
  <% else %>
  <tr>
    <th><%= f.label :picture %></th><td><%= f.file_field :picture %></td>
  </tr>
  <% end %>
  <tr>
    <th><%= f.label :name %></th><td><%= f.text_field :name %></td>
  </tr>
  <tr>
    <th><%= f.label :email %></th><td><%= f.email_field :email %></td>
  </tr>
</table>

<%= f.submit %>
<% end %>
<%= link_to t('view.back'), :back %>
</div>

app/views/users/show.html.erb
<div class="container">
<h2><%= @user.name %>の<%=t('header.mypage') %></h2>
  <div class="user">
    <% if current_user.id == @user.id %>
    <div class="user_show"><%= link_to t('view.edit') , edit_user_path(@user.id) %></div>
    <div class="user_show"><%= link_to t('view.delete'),user_path(@user.id), method: :delete %></div>
    <% end %>

  
    <div class="user_picture">
      <% if @user.picture.url.present? %>
        <div class="user_picture"><%= image_tag @user.picture.url %></div>
      <% else %>
        <div class="user_picture"><%= image_tag 'no_photo.png', size: '50x50' %></div>
      <% end %>
    </div>

    
  </div>
  <% if @recipes.present? %>
  <div class="subject"><%= t('user.post') %></div>
<% end %> 
 <div class="user_recipe">
      <% @recipes.each do |recipe| %>
      <%= link_to recipe_path(recipe.id) do %>
       <div class="recipe_box">
         <div class="picture">
           <% if recipe.picture.url.present? %>
             <div><%= image_tag recipe.picture.url %></div>
           <% else %>
             <div><%= image_tag 'no_photo.png', size: '50x50' %></div>
           <% end %>
         </div>
         <div class="recipe_inf" >
           <ul>
             <li id="inf_1"><%= "#{recipe.shop.name}風" %><%= recipe.name %></li>
             <li id="inf_2"><%= t('view.update') %><%= recipe.updated_at.strftime('%Y/%m/%d') %></li>
           </ul>
         </div>
       </div>
       <% end %>
      <% end %>
    </div>
   
  
<% if @user.id == current_user.id %>
  <% if @recipe_likes.present? %>
  <div class="subject"><%= t('view.like')%></div>
<% end %>
<div class="user_recipe">
  <% @recipe_likes.each do |like| %>
    <%= link_to recipe_path(like.recipe.id) do %>
    <div class="recipe_box">
    <div class="picture">
        <% if like.recipe.picture.url.present? %>
          <div><%= image_tag like.recipe.picture.url %></div>
        <% else %>
          <div><%= image_tag 'no_photo.png', size:'50x50' %></div>
        <% end %>
      </div>

      <div class="recipe_inf">
      <ul>
        <li id="inf_1"><%= "#{like.recipe.shop.name}風" %><%= like.recipe.name %></li>
        <li id="inf_1"><%= t('view.user') %><%= like.recipe.user.name %></li>

      </ul>
      </div>
      </div>
    <% end %>
    <% end %>
  <% end %>
    </div>
    </div>
    </div>